create database DuAn1_CuaHangDienThoai
go
use DuAn1_CuaHangDienThoai
go
CREATE TABLE Hang(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
	Ma VARCHAR(10) NOT NULL,
	TenHang NVARCHAR(30) NOT NULL,
	NgayThem DATE,
	NgaySua DATE
)
-- Tao bang DongSp
CREATE TABLE DongSP(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
	Ma VARCHAR(10) NOT NULL,
	TenDongSP NVARCHAR(50) NOT NULL,
	GiaNhap BIGINT NOT NULL,
	GiaBan BIGINT NOT NULL,
	IdHang UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL FOREIGN KEY REFERENCES dbo.Hang(Id),
	NgayThem DATE,
	NgaySua DATE
)
-- Tao bang CoSo
CREATE TABLE CoSo(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
	Ma VARCHAR(10) NOT NULL,
	Ten NVARCHAR(50) NOT NULL,
	NgayThem DATE,
	NgaySua DATE
)
-- Tao bang CuaHang
CREATE TABLE CuaHang(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
	Ma VARCHAR(10) NOT NULL,
	Ten NVARCHAR(50) NOT NULL,
	DiaChi VARCHAR(MAX) NOT NULL,
	IdCoSo UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL FOREIGN KEY REFERENCES dbo.CoSo(Id),
	NgayThem DATE,
	NgaySua DATE
)
-- Tao bang DungLuong
CREATE TABLE DungLuong(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
	Ma VARCHAR(10) NOT NULL,
	Ten NVARCHAR(10) NOT NULL,
	NgayThem DATE,
	NgaySua DATE
)
-- Tao bang MauSac
CREATE TABLE MauSac(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
	Ma VARCHAR(10) NOT NULL,
	Ten NVARCHAR(50) NOT NULL,
	NgayThem DATE,
	NgaySua DATE
)
-- Tao bang ChiTietSP
CREATE TABLE ChiTietSP(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
	IdDongSP UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL FOREIGN KEY REFERENCES dbo.DongSP(Id),
	IdMauSac UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL FOREIGN KEY REFERENCES dbo.MauSac(Id),
	IdDungLuong UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL FOREIGN KEY REFERENCES dbo.DungLuong(Id),
	IdCuaHang UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL FOREIGN KEY REFERENCES dbo.CuaHang(Id),
	NgayThem DATE,
	NgaySua DATE,
	SoLuong INT NOT NULL,
	TrangThai BIT NOT NULL
)
-- Tao bang ChucVu 
CREATE TABLE ChucVu(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
	Ma VARCHAR(10) NOT NULL,
	Ten VARCHAR(50) NOT NULL,
	NgayThem DATE,
	NgaySua DATE
)
-- Tao bang Rank
CREATE TABLE Rank(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
	Ma VARCHAR(10) NOT NULL,
	Ten NVARCHAR(50) NOT NULL,
	MucChi BIGINT NOT NULL,
	NgayThem DATE,
	NgaySua DATE
)
-- Tao bang NguoiDung 
CREATE TABLE NguoiDung(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
	Ma VARCHAR(10) NOT NULL,
	HoTen NVARCHAR(50) NOT NULL,
	GioiTinh BIT NOT NULL,
	NgaySinh DATE NOT NULL,
	Sdt VARCHAR(10) NOT NULL,
	DiaChi NVARCHAR(MAX),
	ThanhPho NVARCHAR(50) NOT NULL,
	IdChucVu UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL FOREIGN KEY REFERENCES dbo.ChucVu(Id),
	IdRank UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL FOREIGN KEY REFERENCES dbo.Rank(Id),
	NgayThem DATE,
	NgaySua DATE
)
-- Tao bang BaoHanh
CREATE TABLE BaoHanh(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
	Ma VARCHAR(10) NOT NULL,
	Ten NVARCHAR(50) NOT NULL,
	ThoiGian INT,
	Gia BIGINT NOT NULL,
	NgayThem DATE,
	NgaySua DATE
)
-- Tao bang HoaDon 
CREATE TABLE HoaDon(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
	Ma VARCHAR(10) NOT NULL,
	IDNguoiDung UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL FOREIGN KEY REFERENCES dbo.NguoiDung(Id),
	NgayMua DATE NOT NULL,
	Sdt VARCHAR(10) NOT NULL,
	DiaChi NVARCHAR(MAX),
	TinhTrang BIT
)
-- Tao bang ChiTietBaoHanh
CREATE TABLE ChiTietBaoHanh(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
	IdHoaDon UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL FOREIGN KEY REFERENCES dbo.HoaDon(Id),
	IdBaoHanh UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL FOREIGN KEY REFERENCES dbo.BaoHanh(Id),
	NgayBaoHanh DATE NOT NULL,
	NgayKetThuc DATE NOT NULL
)
-- Tao bang HoaDonChiTiet
CREATE TABLE HoaDonChiTiet(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	IdHoaDon UNIQUEIDENTIFIER DEFAULT NEWID() FOREIGN KEY REFERENCES dbo.HoaDon(Id) NOT NULL,
	IdSanPham UNIQUEIDENTIFIER DEFAULT NEWID() FOREIGN KEY REFERENCES dbo.ChiTietSP(Id) NOT NULL,
	SoLuong INT NOT NULL,
	DonGia BIGINT NOT NULL,
	ThanhTien BIGINT NOT NULL
)
-- Tao bang GioHang
CREATE TABLE GioHang(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Ma VARCHAR(10) NOT NULL,
	IdNguoiDung UNIQUEIDENTIFIER DEFAULT NEWID() FOREIGN KEY REFERENCES dbo.NguoiDung(Id) NOT NULL,
	NgayTao DATE NOT NULL,
	TrangThai BIT not null 
)
-- Tao bang GioHangChiTiet
CREATE TABLE GioHangChiTiet(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	IdGioHang UNIQUEIDENTIFIER DEFAULT NEWID() FOREIGN KEY REFERENCES dbo.GioHang(Id) NOT NULL,
	IdSanPham UNIQUEIDENTIFIER DEFAULT NEWID() FOREIGN KEY REFERENCES dbo.ChiTietSP(Id) NOT NULL,
	SoLuong INT NOT NULL,
	DonGia BIGINT NOT NULL,
	ThanhTien BIGINT NOT NULL
)
-- Tao bang Account
CREATE TABLE Account(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	UserName VARCHAR(50) NOT NULL,
	Pass varchar(18) not null,
	IdNguoiDung UNIQUEIDENTIFIER DEFAULT NEWID() FOREIGN KEY REFERENCES dbo.NguoiDung(Id) NOT NULL,
)
